name: Release

on:
  push:
    tags:
      - 'v*'

# Releases code whne tagged, modifed from https://www.youtube.com/watch?v=-0vWW-ymlfw
jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
